# Generated by Django 3.1.4 on 2020-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/profile_pics/default.webp ', upload_to='img/profile_pics'),
        ),
    ]
