# Generated by Django 3.1.4 on 2020-12-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='img/profile_pics/default.webp', upload_to='img/profile_pics'),
        ),
    ]
