# Generated by Django 3.1.4 on 2020-12-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('Pemrograman', 'Pemrograman'), ('Mikrotik', 'Mikrotik'), ('Sistem Operasi', 'Sistem Operasi'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50)),
                ('thumbnail', models.ImageField(default='img/default.webp', upload_to='img/%Y/%m/%d')),
                ('excerpt', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
