# Generated by Django 3.1.4 on 2020-12-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201207_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Desain Grafis', 'Desain Grafis'), ('Mikrotik', 'Mikrotik'), ('Pemrograman', 'Pemrograman'), ('Sistem Operasi', 'Sistem Operasi'), ('Lainnya', 'Lainnya')], default='Lainnya', max_length=50),
        ),
    ]
